[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
arcade = "34ChFkgCd7JXnVEW3ityB8GvvUcXH1kusH1cz2SJwR1H"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
